server.port=8090

# Database — vars from docker-compose .env
spring.datasource.url=jdbc:sqlserver://${DB_HOST}:${DB_PORT};databaseName=${DB_NAME};encrypt=false;trustServerCertificate=true
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver

spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=false

# CORS
app.cors.allowed-origins=${CORS_ORIGINS}
server.servlet.session.cookie.same-site=Lax

# Azure AD — override via env if needed
# spring.security.oauth2.client.registration.azure.client-id=${AZURE_CLIENT_ID}
# spring.security.oauth2.client.registration.azure.client-secret=${AZURE_CLIENT_SECRET}

# Bypass auto-discovery — URLs statiques Azure AD (évite l'appel réseau au démarrage)
spring.security.oauth2.client.provider.azure.issuer-uri=https://login.microsoftonline.com/d4a96e86-7cb0-4ad5-8ad8-2f613af98ce8/v2.0
spring.security.oauth2.client.provider.azure.authorization-uri=https://login.microsoftonline.com/${AZURE_TENANT_ID}/oauth2/v2.0/authorize
spring.security.oauth2.client.provider.azure.token-uri=https://login.microsoftonline.com/${AZURE_TENANT_ID}/oauth2/v2.0/token
spring.security.oauth2.client.provider.azure.jwk-set-uri=https://login.microsoftonline.com/${AZURE_TENANT_ID}/discovery/v2.0/keys
spring.security.oauth2.client.provider.azure.user-info-uri=https://graph.microsoft.com/oidc/userinfo
spring.security.oauth2.client.provider.azure.user-name-attribute=sub

# Fix forward headers
server.forward-headers-strategy=NATIVE